settings:
  plugin.tx_formconsent.view.templateRootPath:
    default: ''
    label: 'Path to template root (FE)'
    type: string
  plugin.tx_formconsent.view.partialRootPath:
    default: ''
    label: 'Path to template partials (FE)'
    type: string
  plugin.tx_formconsent.view.layoutRootPath:
    default: ''
    label: 'Path to template layouts (FE)'
    type: string
  plugin.tx_formconsent.persistence.storagePid:
    default: 0
    label: 'Default storage PID for consent data'
    type: int
