categories:
  form_consent: ~
  form_consent.templates:
    parent: form_consent
  form_consent.persistence:
    parent: form_consent

settings:
  plugin.tx_formconsent.view.templateRootPath:
    default: ''
    type: string
    category: form_consent.templates
  plugin.tx_formconsent.view.partialRootPath:
    default: ''
    type: string
    category: form_consent.templates
  plugin.tx_formconsent.view.layoutRootPath:
    default: ''
    type: string
    category: form_consent.templates
  plugin.tx_formconsent.persistence.storagePid:
    default: 0
    type: int
    category: form_consent.persistence
