version: '3.6'

services:
  web:
    depends_on:
      - db
      - selenium
  selenium:
    container_name: ddev-${DDEV_SITENAME}-selenium
    image: seleniarm/standalone-chromium:4.1.2-20220227
    networks:
      default:
        aliases:
          - web
      ddev_default:
    volumes:
      - /dev/shm:/dev/shm
    external_links:
      - ddev-router:$DDEV_HOSTNAME
