name: CGL
on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
    branches:
      - main

jobs:
  cgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2, composer-require-checker, composer-unused, cs2pr
          coverage: none

      # Validation
      - name: Validate composer.json
        run: composer validate

      # Install dependencies
      - name: Install Composer dependencies
        run: |
          composer require --no-progress --no-plugins --no-scripts \
            typo3/cms-dashboard:"~12.4.2 || ~13.4.0" \
            typo3/cms-scheduler:"~12.4.2 || ~13.4.0"

      # Check Composer dependencies
      - name: Check dependencies
        run: composer-require-checker check --config-file Tests/CGL/dependency-checker.json
      - name: Reset composer.json
        run: git checkout composer.json composer.lock
      - name: Re-install Composer dependencies
        uses: ramsey/composer-install@v3
      - name: Check for unused dependencies
        run: composer-unused

      # Linting
      - name: Lint composer.json
        run: composer cgl lint:composer
      - name: Lint Editorconfig
        run: composer cgl lint:editorconfig
      - name: Lint PHP
        run: composer cgl lint:php -- --format=checkstyle | cs2pr
      - name: Lint TypoScript
        run: composer cgl lint:typoscript

      # SCA
      - name: SCA PHP
        run: composer cgl sca:php -- --error-format github

      # Migration
      - name: Rector migration
        run: composer cgl migration:rector -- --dry-run

      # Documentation
      - name: Check documentation build
        run: |
          mkdir -p .Build/docs
          composer docs:build -- --no-progress --fail-on-log
