name: CGL
on:
  push:
    branches:
      - main
      - 1.x
  pull_request:
    branches:
      - '**'

jobs:
  cgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          # @todo switch back to composer-unused 0.8 once https://github.com/composer-unused/composer-unused/issues/444 is resolved
          tools: composer:v2, composer-require-checker, composer-unused:0.7
          coverage: none

      # Validation
      - name: Validate composer.json
        run: composer validate --no-check-lock

      # Install dependencies
      - name: Install Composer dependencies
        run: |
          composer require --no-progress --no-plugins \
            typo3/cms-dashboard:"~11.5.16" \
            typo3/cms-scheduler:"~11.5.16"

      # Check Composer dependencies
      - name: Check dependencies
        run: composer-require-checker check --config-file dependency-checker.json
      - run: composer install --no-progress
      - name: Check for unused dependencies
        run: composer-unused

      # Linting
      - name: Lint composer.json
        run: composer lint:composer -- --dry-run
      - name: Lint Editorconfig
        run: .Build/bin/ec -e .Build
      - name: Lint PHP
        run: composer lint:php -- --dry-run
      - name: Lint TypoScript
        run: composer lint:typoscript -- --fail-on-warnings

      # SCA
      - name: SCA PHP
        run: composer sca:php -- --error-format github

      # Migration
      - name: Run Rector migration
        run: composer migration:rector -- --dry-run
