name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: 'Prepare workflow'
    uses: eliashaeussler/gha/.github/workflows/preparation.yaml@5344de65c90275de4c729d973f1fe7246ea23ee1 # 0.6.3

  checks:
    name: 'Checks'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      security-events: write

    uses: eliashaeussler/gha/.github/workflows/checks.yaml@5344de65c90275de4c729d973f1fe7246ea23ee1 # 0.6.3
    with:
      # We use the minimum supported PHP version
      php-version: 8.2 # renovate-ignore

  tests:
    name: 'Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }} & ${{ matrix.dependencies }} dependencies)'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        typo3-version: ["13.4", "14.3"]
        dependencies: ["highest", "lowest"]

    uses: eliashaeussler/gha/.github/workflows/typo3-tests.yaml@5344de65c90275de4c729d973f1fe7246ea23ee1 # 0.6.3
    with:
      php-version: ${{ matrix.php-version }}
      typo3-version: ${{ matrix.typo3-version }}
      dependencies: ${{ matrix.dependencies }}
      ddev-version: '1.25.2'

  test-coverage:
    name: 'Test coverage'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    uses: eliashaeussler/gha/.github/workflows/typo3-test-coverage.yaml@5344de65c90275de4c729d973f1fe7246ea23ee1 # 0.6.3
    with:
      ddev-version: '1.25.2'

  crowdin:
    name: 'Synchronize with Crowdin'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    secrets:
      CROWDIN_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/crowdin.yaml@5344de65c90275de4c729d973f1fe7246ea23ee1 # 0.6.3
    with:
      project-id: 477445
