name: 'Merge Renovate branch'

on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: [CI]
    types: [completed]
    branches: ['renovate/*']

permissions:
  contents: read

jobs:
  merge:
    name: 'Merge Renovate branch'

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    secrets:
      MERGE_TOKEN: ${{ secrets.REBUILD_ASSETS_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/merge.yaml@c5d066ebd1c130e32d87bf7e7c8a1c3ca64bd14b # 0.8.2
