name: Tests
on: [push, pull_request]

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} & TYPO3 ${{ matrix.typo3-version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - typo3-version: "10.4"
            php-version: "7.4"
          - typo3-version: "11.5"
            php-version: "7.4"
          - typo3-version: "11.5"
            php-version: "8.0"
          - typo3-version: "11.5"
            php-version: "8.1"
            coverage: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: none

      # Setup DDEV
      - name: Setup DDEV
        uses: jonaseberle/github-action-setup-ddev@v1
        with:
          autostart: false
      - name: Configure and start DDEV
        run: |
          ddev config --project-type=typo3 --php-version=${{ matrix.php-version }} --xdebug-enabled=true
          ddev start

      # Install dependencies
      - name: Install TYPO3 and Composer dependencies
        run: ddev composer require typo3/cms-core:"^${{ matrix.typo3-version }}" --no-progress

      # Run tests
      - name: Run tests
        run: |
          ddev composer test:ci
          ddev composer test:ci:merge

      # Report coverage
      - name: Fix coverage path
        working-directory: .Build/log/coverage
        run: sed -i 's#/var/www/html#${{ github.workspace }}#g' clover.xml
        if: ${{ matrix.coverage && github.event_name == 'pull_request' }}
      - name: CodeClimate report
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ github.workspace }}/.Build/log/coverage/clover.xml:clover
        if: ${{ matrix.coverage && github.event_name == 'pull_request' }}
      - name: codecov report
        uses: codecov/codecov-action@v2
        with:
          directory: .Build/log/coverage
          fail_ci_if_error: true
          verbose: true
        if: ${{ matrix.coverage && github.event_name == 'pull_request' }}

      # Save acceptance reports
      - uses: actions/upload-artifact@v3
        with:
          name: acceptance-reports-${{ matrix.php-version }}-${{ matrix.typo3-version }}
          path: .Build/log/acceptance-reports
        if: failure()

  tests-lowest:
    name: '[test-lowest] PHP ${{ matrix.php-version }} & TYPO3 ${{ matrix.typo3-version }}'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - typo3-version: "10.4"
            php-version: "7.4"
          - typo3-version: "11.5"
            php-version: "7.4"
          - typo3-version: "11.5"
            php-version: "8.0"
          - typo3-version: "11.5"
            php-version: "8.1"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: none

      # Setup DDEV
      - name: Setup DDEV
        uses: jonaseberle/github-action-setup-ddev@v1
        with:
          autostart: false
      - name: Configure and start DDEV
        run: |
          ddev config --project-type=typo3 --php-version=${{ matrix.php-version }}
          ddev start

      # Install dependencies
      - name: Install TYPO3 and Composer dependencies
        run: ddev composer require typo3/cms-core:"^${{ matrix.typo3-version }}" --prefer-lowest --no-progress

      # Run tests
      - name: Run tests
        run: ddev composer test

      # Save acceptance reports
      - uses: actions/upload-artifact@v3
        with:
          name: acceptance-reports-${{ matrix.php-version }}-${{ matrix.typo3-version }}-lowest
          path: .Build/log/acceptance-reports
        if: failure()
