name: Tests
on: [push, pull_request]

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} & TYPO3 ${{ matrix.typo3-version }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - typo3-version: 10.4
            php-version: 7.4
          - typo3-version: 11.5
            php-version: 7.4
          - typo3-version: 11.5
            php-version: 8.0
          - typo3-version: 11.5
            php-version: 8.1
            coverage: 1
    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: '127.0.0.1'
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug

      # Start MySQL service
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      # Define Composer cache
      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Define Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: tests-php-${{ matrix.php-version }}-typo3-${{ matrix.typo3-version }}
          restore-keys: |
            tests-php-${{ matrix.php-version }}-typo3-

      # Install dependencies
      - name: Install TYPO3 and Composer dependencies
        run: composer require typo3/cms-core:"^${{ matrix.typo3-version }}" --no-progress

      # Run tests
      - name: Run tests
        run: |
          composer test:ci -- --coverage-text
          composer test:ci:merge

      # Report coverage
      - name: CodeClimate report
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ github.workspace }}/.Build/log/coverage/clover.xml:clover
        if: ${{ matrix.coverage }}
      - name: codecov report
        uses: codecov/codecov-action@v2
        with:
          directory: .Build/log/coverage
          fail_ci_if_error: true
          verbose: true
        if: ${{ matrix.coverage }}

  tests-lowest:
    name: '[test-lowest] PHP ${{ matrix.php-version }} & TYPO3 ${{ matrix.typo3-version }}'
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - typo3-version: 10.4
            php-version: 7.4
          - typo3-version: 11.5
            php-version: 7.4
          - typo3-version: 11.5
            php-version: 8.0
          - typo3-version: 11.5
            php-version: 8.1
    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: '127.0.0.1'
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug

      # Start MySQL service
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      # Define Composer cache
      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Define Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: tests-lowest-php-${{ matrix.php-version }}-typo3-${{ matrix.typo3-version }}
          restore-keys: |
            tests-lowest-php-${{ matrix.php-version }}-typo3-

      # Install dependencies
      - name: Install TYPO3 and Composer dependencies
        run: composer require typo3/cms-core:"^${{ matrix.typo3-version }}" --prefer-lowest --no-progress

      # Run tests
      - name: Run tests
        run: composer test:ci -- --coverage-text
